### ISSUE TITLE
Bug avec get_term_id_from_meta

### ISSUE THREAD

**Issue by Rahe** [BeAPI/meta-for-taxonomies#1]
Quand on veut récupérer un terme à partir de sa valeur dans une taxonomie, la fonction get_term_id_from_meta ne renvoie pas la bonne valeur si la valeur recherchée est dans plusieurs termes.
Cela vient du fait que la fonction get_term_taxonomy_id_from_meta ne prend pas en compte la taxonomie.

**Comment by herewithme** [comment]
Implemented on https://github.com/herewithme/meta-for-taxonomies/commit/49b6b07a2a5fff2a9f9da5572881090e4386c039

Thanks for report !
