### ISSUE TITLE
Cache group used in wp_cache_* functions should be 'term_taxo_meta' not 'term_taxometa'

### ISSUE THREAD

**Issue by artuze** [BeAPI/meta-for-taxonomies#2]
`update_termmeta_cache` uses a `$meta_type` of 'term_taxo' when it calls `update_meta_cache`. In `update_meta_cache`, it appends '_meta' to the `$meta_type` to generate the `$cache_key`, loading everything into the 'term_taxo_meta' cache group.

The plugin has a number of calls to `wp_cache_set`, `wp_cache_get`, and `wp_cache_delete` all using 'term_taxometa'. I noticed it by trying to use `get_term_custom` and backtracking when it wasn't getting values I could see in the database it was saving.

Doesn't seem to affect retrieving single term meta values with `get_term_meta` since that is using the core `get_metadata` function that handles appending the correct '_meta' string to the `$meta_type`.

**Comment by herewithme** [comment]
Fixed on https://github.com/herewithme/meta-for-taxonomies/commit/9d9bbd6074e49842eeed4241984aaccf90713f41

Thanks for report !

**Comment by artuze** [comment]
Awesome! Very cool plugin, by the way. I can see myself using it a lot more after this project. :thumbsup:
