### ISSUE TITLE
Function name clashes with WordPress 4.4

### ISSUE THREAD

**Issue by Screenfeed** [BeAPI/meta-for-taxonomies#5]
Hi there.

Here what I spotted so far: `update_termmeta_cache()`, `add_term_meta()`, `delete_term_meta()`, `get_term_meta()` and `update_term_meta()`.
But the worst part is that we also have non-matching function signatures: the plugin functions use `$taxonomy` as first parameter, but WordPress doesn't.

**Comment by herewithme** [comment]
SHIT !

**Comment by Screenfeed** [comment]
?

**Comment by herewithme** [comment]
No solution is really possible ... Edit behavioral functions break the compat, the arrival of WP 4.4, makes it incompatible my implementation.

Anyway, crap.

**Comment by Screenfeed** [comment]
I guess the only thing would be this at the beginning of the plugin:
`if ( function_exists( 'get_term_meta' ) {
    return;
}`
Things would break because of the non-matching function signatures, but not trigger a fatal error.

**Comment by herewithme** [comment]
Hop !
https://github.com/BeAPI/meta-for-taxonomies/commit/d59dd5b8bd66d6e610ac9ae28f514281bd463407

**Comment by Screenfeed** [comment]
Easy pizi ^^'
Would me too much to ask an update on the WordPress repository? :3
